### ISSUE TITLE
Consider a way to represent color spaces

### ISSUE THREAD

**Issue by slaren** [brendanzab/color-rs#1]
We need a way to represent color spaces. It may be desirable to have color spaces defined independantly of color formats, ideally allowing us to have color types defined as a combination of channel type, color format and color space, such as:

``` rust
// color channels
trait Channel { .. }

// color spaces
enum Linear {}
enum sRGB {}

trait ColorSpace { .. }

impl ColorSpace for Linear { .. }
impl ColorSpace for SRGB { .. }

// color formats
struct RGB<T: Channel, S: ColorSpace> { r: T, g: T, b: T }

// color types
trait Color<T: Channel, S: ColorSpace> { .. }

impl<T: Channel, S: ColorSpace> Color<T, S> for RGB<T, S> { .. }

// possible color types: RGB<u8, sRGB>, RGB<f32, Linear>, etc
```

However, this may not work well in practice since color spaces are often tied to their own color formats.

**Comment by flying-sheep** [comment]
there is another color library that has them: [retep998/colors-rs](https://github.com/retep998/colors-rs)

also there’s rudimentary color structs in [PistonDevelopers/image](https://github.com/PistonDevelopers/image/blob/master/src/color.rs)

I’d love to see this stuff unified!

**Comment by flying-sheep** [comment]
good info is to be found [here](http://www.brucelindbloom.com/index.html?ColorCalcHelp.html) and [here](http://www.brucelindbloom.com/index.html?Equations.html)

**Comment by retep998** [comment]
I'll support any initiative to have a standard way of working with colors and colorspaces, as long as it is done well.

**Comment by flying-sheep** [comment]
do you have any opinions on #24?

**Comment by bjz** [comment]
Awesome! I am just finishing up a massive cleanup of noise-rs with the help of others, and I think it is well time for color-rs to get some love. I'll see what is in colors-rs and am happy to work with you to improve it.

**Comment by flying-sheep** [comment]
since this is an info dump as well as an discussion: [this project](https://github.com/CarVac/filmulator-gui) makes advanced use of color models (not in rust).

i think if we could elegantly support that use case, we’re set.
